export { closedHandGesture } from './closedHandGesture'
export { okGesture } from './okGesture'
export { victoryGesture } from './victoryGesture'
export { fingerUp } from './fingerUp'
export { fingerDown } from './fingerDown'
